sudo: required
services:
  - docker

script:
  - docker build -t vani33/node .
  - docker images vani33/node
  
before_deploy:
  - docker login -u vani33 -p Vanisree@2218

deploy:
  provider: script
  script: docker push vani/node
  on:
    branch: master
